### ISSUE TITLE
Unable to access Kibana dashboard hosted on EC2 in `cnbvpc-VpnSecurityGroup`

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks-Challenges/cnb-aws-infra#4]
### Problem description

I created an EC2 instance named `ptc-elk` in the AWS account `CnbAccount`. This instance is running the ELK stack [Sage-Bionetworks/docker-elk](https://github.com/Sage-Bionetworks/docker-elk). The Kibana dashboard is listening to TCP connections on port 5601. The issue is that I cannot access the dashboard at the address `http://10.255.22.107:5601`, where `10.255.22.107` is the private IPv4 address of the instance.

Here are information relative to this networking issue:

- Security groups:
  - sg-0807a0e374542affd (cnbvpc-VpnSecurityGroup-JBXT9AUVDXCA)
    - Inbound rules:
      - Type: All traffic, Description: Allow all VPN traffic

I'm assuming that this configuration should enable me to access the private IPv4 address of the instance on all ports when connected to Sage VPN.

#### Steps to reproduce the issue

1. Connect to Sage VPN.
2. Open your browser at the address `http://10.255.22.107:5601`.
3. On FireFox, the message displayed is `The connection has timed out`.

#### Expected behavior

- Successfully access the Kibana dashboard

#### Extra information

-

**Comment by thomasyu888** [comment]
Currently that VPN security group isn't actually set up to work with the VPN. (Due to our most recent shift into the new AWS VPN).  My suggestion is to ping #sageit for them to prioritize this.

**Comment by tschaffter** [comment]
Reported this GH ticket in Jira [here](https://sagebionetworks.jira.com/browse/IT-2045?atlOrigin=eyJpIjoiYjYzNTVhMzhlMzc0NDdlM2EwOGQxZTk2MjA2Njg2OTQiLCJwIjoiaiJ9).

**Comment by tschaffter** [comment]
Forwarding Kibana's port using AWS SSM works.
